### ISSUE TITLE
Show entire image in thumbnail without cropping

### ISSUE THREAD

**Issue by acstll** [medienbaecker/kirby-images#43]
Is that possible?

(Thank you for such a great plugin)

**Comment by acstll** [comment]
From seeing this https://github.com/medienbaecker/kirby-images/blob/master/fields/images/template.php#L49 I believe it is not possible…

Would you be open for a PR?

**Comment by medienbaecker** [comment]
I decided to use the 400x266 thumbnail as this one gets created for the "files" view anyway. Thumbnail creation in the Kirby Panel is not very fast and slows down the panel a lot. Especially because the page load gets delayed without a progress bar, this feels bad for panel users.

It wouldn't be that difficult to add a `crop: false` option and adjust the CSS, though.
