### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by medienbaecker** [medienbaecker/kirby-images#5]
Maybe options like 

- Crop ratio
- Page
- Sortable
- readonly
- ...

would be helpful.

**Comment by Targoran** [comment]
This plugin looks really promising as a solution for slideshows. Another option I would like to see is to set the image preview size to something even smaller so more images fit into the viewport - like 6 instead of 3 in a row for example.

**Comment by jenstornell** [comment]
I've not tried this plugin yet but it looks awesome.

If you want option ideas I have some in mind.

- Like @Targoran, number of images in a row could be useful.
- Limit could be useful in some cases (like the structure field).

**Comment by medienbaecker** [comment]
Thanks a lot for your suggestions @Targoran and @jenstornell! I'm not sure how to include the duplicate images function, do you think holding ctrl/alt for that would be intuitive? Or rather with a field wide option?

At some point I'd also like to display the file fields directly on the page. Right now you have to go to the file edit screen to enter stuff like captions. It's hard to implement though, as it would be a `<form>` in a `<form>`. If anyone has an idea how to solve this, please let me know. I think something like that would be super cool:

![filefields](https://cloud.githubusercontent.com/assets/7975568/25743833/b6f0f3ea-3196-11e7-9b6c-71c81744fcff.gif)

**Comment by jenstornell** [comment]
With duplicate images I just mean allow to drag the same image twice. Let the user select the same image twice in the dropdown. I don't have a real case for it so I'm not really sure of the importance of it.

About adding meta data to the image. I thought about that as well but because I'm aware of how hard it is to implement, I did not add it to my list.

**Comment by Targoran** [comment]
Of course it would be cool to use custom captions and meta for images inside the gallery, but I think as a start it would be enough to just use the custom image fields for this purpose. As the images are just image objects, it's easy to access these information if provided.

**Comment by jenstornell** [comment]
The more I think about it the more I agree with @Targoran. We expect to get to the image edit page, because that's how the panel does it. If the Panel in the future add a new feature with a modal, maybe add it at that point of time? Else it would be more complex and less of what we expect when we click.

**Comment by medienbaecker** [comment]
Thanks for your input guys. I totally agree, it may be confusing to have an identical icon in an almost identical image grid do a completely different thing.

**Comment by lukaskleinschmidt** [comment]
Are there still plans to implement a limit option for this field?

**Comment by medienbaecker** [comment]
I don't have anything planned as I didn't have a use case yet. But it can definitely be useful for some projects. I'll add a new issue for that 👍
